version : "3"

services:
  cache:
    container_name: "cache"
    image: redis
    restart: always
    expose:
     - "6379"
    ports:
     - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - eva-network
  db:
    container_name: "db"
    image: library/postgres:15
    restart: always
    env_file:
      - .dev.env
    environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
     - "5432"
    ports:
     - "5432:5432"
    volumes:
     - db-data:/var/lib/postgresql/data
    networks:
     - eva-network


networks:
  eva-network:

volumes:
  cache:
      driver: local
  db-data: